# Site settings
name: Joanna Yoo
title: Joanna Yoo
description:
url: https://joannayoo0117.github.io/
baseurl: ''
email: hi@joannayoo.dev
logo: https://joannayoo0117.github.io/images/logo.png
resume: https://joannayoo0117.github.io/resume.pdf
social:
  - title: email
    url: mailto:hi@joannayoo.dev
    name: hi@joannayoo.dev
  - title: twitter
    url: https://twitter.com/_joanna_yoo
    name: _joanna_yoo
  - title: github
    url: https://github.com/joannayoo0117
    name: joannayoo0117
  - title: linkedin
    url: https://www.linkedin.com/in/joannayoo
    name: joannayoo

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
